spring.application.name=aidemo
server.address=0.0.0.0

# Oracle DB Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.password=hr
spring.datasource.username=hr
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=gairola
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp
server.ssl.enabled=true
