
server:
  port: 9000
  address: 0.0.0.0

spring:
  application:
    name: ichr-service
    
logging:
  level:
    root: INFO
  pattern:
    console: '{"service":"ichr-service", "timestamp":"%d{yyyy-MM-dd HH:mm:ss}", "level":"%p", "message":"%m"}'
  file:
    name: /var/log/ichr-service.log
                             
management:
       endpoints:
            web:
              exposure:
                     include:*


