# Application Name
spring.application.name=llmApp

# Server Port
server.port=7777
#ollama run llama3
#ollama pull nomic-embed-text
# Thymeleaf (optional but recommended)
spring.thymeleaf.cache=false

# Logging (optional - useful for debugging)
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# Oracle DB Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.password=hr
spring.datasource.username=hr
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true