# ==========================================
# ORACLE
# ==========================================
spring.application.name=auth-server

server.port=9000
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=HR
spring.datasource.password=hr
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# ==========================================
# JPA
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

jwt.secret=MyVeryStrongSecretKeyForJwtAuthentication123456789
jwt.expiration=3600000
spring.thymeleaf.cache=false